//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Entidaddes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalles_nomina
    {
        public int ID_Detalle_Nomina { get; set; }
        public int id_Nomina { get; set; }
        public int ID_Empleado { get; set; }
        public int ID_Trancaccion { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Nomina Nomina { get; set; }
        public virtual Transaccion Transaccion { get; set; }
    }
}
