//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Entidaddes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Detalles_nomina = new HashSet<Detalles_nomina>();
            this.Nomina = new HashSet<Nomina>();
        }
    
        public int ID_Empleado { get; set; }
        public int Cedula { get; set; }
        public string Empleado_Nombre { get; set; }
        public int Id_Depart6amento { get; set; }
        public int Id_Puesto { get; set; }
        public int Salario { get; set; }
        public int ID_Igreso { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalles_nomina> Detalles_nomina { get; set; }
        public virtual Puesto Puesto { get; set; }
        public virtual Tipos_Ingresos Tipos_Ingresos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nomina> Nomina { get; set; }
    }
}
