//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using Capa_Entidaddes;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NominaEntities : DbContext
    {
        public NominaEntities()
            : base("name=NominaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
        }
    
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Detalles_nomina> Detalles_nomina { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Nomina> Nomina { get; set; }
        public virtual DbSet<Puesto> Puesto { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tipos_Ingresos> Tipos_Ingresos { get; set; }
        public virtual DbSet<Transaccion> Transaccion { get; set; }
    }
}
